require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Valkey cache store for development
  config.cache_store = :redis_cache_store, {
    url: ENV.fetch('VALKEY_URL', 'redis://localhost:6379/1'),
    reconnect_attempts: 3,
    timeout: 1.0,
    pool: { size: 10 }
  }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false
  
  # Letter Opener Web でメール確認
  config.action_mailer.delivery_method = :letter_opener_web
  
  # 環境変数による自動切り替え（HTTP/HTTPS対応）
  host_name = ENV.fetch('HOST_NAME', 'localhost')
  host_port = ENV.fetch('HOST_PORT', '443').to_i

  if host_port == 443 || host_port == 4443
    # HTTPS環境
    config.force_ssl = true
    config.ssl_options = { redirect: false }
    config.hosts = [host_name, "host.docker.internal"]

    # ポート番号が443の場合は省略、それ以外は明示
    if host_port == 443
      Rails.application.routes.default_url_options = {
        host: host_name,
        protocol: 'https'
      }
    else
      Rails.application.routes.default_url_options = {
        host: host_name,
        port: host_port,
        protocol: 'https'
      }
    end
  else
    # HTTP環境（戻す場合）
    Rails.application.routes.default_url_options = {
      host: host_name,
      port: host_port
    }
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # nginx proxy support - trust X-Forwarded headers
  config.force_ssl = false
  config.action_controller.forgery_protection_origin_check = false
  
  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
